// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLSs6JJZ4nelUNt_m30JnTBnpryY5m8J4',
    appId: '1:916085757078:web:8901e3f5871791ec4f1eb7',
    messagingSenderId: '916085757078',
    projectId: 'iskomate-f149c',
    authDomain: 'iskomate-f149c.firebaseapp.com',
    storageBucket: 'iskomate-f149c.firebasestorage.app',
    measurementId: 'G-XSWDP9HEJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNgGqOvPf3wgKBQcGjXxdARFF6aChFoFg',
    appId: '1:916085757078:android:57b8cea78e0f02c14f1eb7',
    messagingSenderId: '916085757078',
    projectId: 'iskomate-f149c',
    storageBucket: 'iskomate-f149c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0CLMdGtGEkNSwyZ8hRrlU-AAbFk84h3k',
    appId: '1:916085757078:ios:8187e6847d3d4f854f1eb7',
    messagingSenderId: '916085757078',
    projectId: 'iskomate-f149c',
    storageBucket: 'iskomate-f149c.firebasestorage.app',
    iosBundleId: 'com.example.iskomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0CLMdGtGEkNSwyZ8hRrlU-AAbFk84h3k',
    appId: '1:916085757078:ios:8187e6847d3d4f854f1eb7',
    messagingSenderId: '916085757078',
    projectId: 'iskomate-f149c',
    storageBucket: 'iskomate-f149c.firebasestorage.app',
    iosBundleId: 'com.example.iskomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLSs6JJZ4nelUNt_m30JnTBnpryY5m8J4',
    appId: '1:916085757078:web:9bd70595ef66feb54f1eb7',
    messagingSenderId: '916085757078',
    projectId: 'iskomate-f149c',
    authDomain: 'iskomate-f149c.firebaseapp.com',
    storageBucket: 'iskomate-f149c.firebasestorage.app',
    measurementId: 'G-J7XMYSC7QP',
  );
}
